################################
##    Davey's Mango Config    ##
## use at your own risk (o_0) ##
################################
#
# structure loosely follows the config documentation at https://mangowm.github.io/docs
# all source-optional files are setup-dependent! you will find these in the optional folder. take them out into the root mango folder as needed.
# alaquake-framework.conf uses the framework logo key to open terminal on laptop
# alaquake.conf by default uses F12
#

# autostart
source=./autostart.conf 

# display settings
source-optional=./esther.conf
source-optional=./linus-torvalds-computer-real.conf

# inputs
source=./inputs.conf

# miscellaneous
source=./misc.conf

# theme
source=./theme.conf

# layout settings
source=./layouts.conf 

# dumbass annoying rules n shit
source=./rules.conf 

# kinky shit (binds)
source=./keys.conf 
source=./otherbinds.conf 

# quake-style terminal (using alacritty) 
source-optional=./alaquake-framework.conf
source-optional=./alaquake.conf
