##############
## Keybinds ##
##############
#
# keybind philosophy: make binds and hope it makes sense
# modifiers: SUPER, CTRL, ALT, SHIFT, NONE (combine with +)
#
# TODO: scratchpad, if you feel like it.
# 

#######################
## WINDOW MANAGEMENT ##
#######################

# close app
bind=SUPER,Q,killclient

# toggle float
bind=SUPER,V,togglefloating

# fullscreen toggle
bind=NONE,F11,togglefullscreen

########################
## FOCUS AND MOVEMENT ##
########################

# shift thine focus
bind=SUPER,Left,focusdir,left
bind=SUPER,Right,focusdir,right
bind=SUPER,Up,focusdir,up
bind=SUPER,Down,focusdir,down

# shift thine windows
bind=SUPER+SHIFT,Left,exchange_client,left
bind=SUPER+SHIFT,Right,exchange_client,Right
bind=SUPER+SHIFT,Up,exchange_client,up
bind=SUPER+SHIFT,Down,exchange_client,down

# resize thine windows
bind=SUPER+CTRL,Left,resizewin,-20,0
bind=SUPER+CTRL,Right,resizewin,20,0
bind=SUPER+CTRL+SHIFT,Left,resizewin,-40,0
bind=SUPER+CTRL+SHIFT,Right,resizewin,40,0

#######################
## TAGS AND MONITORS ##
#######################

# View Tag
bind=SUPER,1,view,1
bind=SUPER,2,view,2
bind=SUPER,3,view,3
bind=SUPER,4,view,4
bind=SUPER,5,view,5
bind=SUPER,6,view,6
bind=SUPER,7,view,7
bind=SUPER,8,view,8
bind=SUPER,9,view,9

# Move to Tag
bind=SUPER+SHIFT,1,tag,1,1
bind=SUPER+SHIFT,2,tag,2,1
bind=SUPER+SHIFT,3,tag,3,1
bind=SUPER+SHIFT,4,tag,4,1
bind=SUPER+SHIFT,5,tag,5,1
bind=SUPER+SHIFT,6,tag,6,1
bind=SUPER+SHIFT,7,tag,7,1
bind=SUPER+SHIFT,8,tag,8,1
bind=SUPER+SHIFT,9,tag,9,1

#############
## LAYOUTS ##
#############

# i yearn for no changes in layout, for scroller is perfect and will never need modification.

############
## SYSTEM ##
############

# SUMMON THE APPS
bind=SUPER,Return,spawn,alacritty
bind=SUPER,Space,spawn,fuzzel

# reload config
bind=SUPER,R,reload_config

# log out / exit mangowm
bind=SUPER+CTRL+SHIFT,Q,quit

# you already know what alt tab does
bind=ALT,Tab,toggleoverview

####################
## MEDIA CONTROLS ##
####################

# brightness
bind=NONE,XF86MonBrightnessUp,spawn,brightnessctl s +2%
bind=NONE,XF86MonBrightnessDown,spawn,brightnessctl s 2%-

# volume
bind=NONE,XF86AudioRaiseVolume,spawn,wpctl set-volume @DEFAULT_SINK@ 5%+
bind=NONE,XF86AudioLowerVolume,spawn,wpctl set-volume @DEFAULT_SINK@ 5%-
bind=NONE,XF86AudioMute,spawn,wpctl set-mute @DEFAULT_SINK@ toggle
bind=SHIFT,XF86AudioMute,spawn,wpctl set-mute @DEFAULT_SOURCE@ toggle

# playback
bind=NONE,XF86AudioNext,spawn,playerctl next
bind=NONE,XF86AudioPrev,spawn,playerctl previous
bind=NONE,XF86AudioPlay,spawn,playerctl play-pause
