#############
## Layouts ##
#############

# Scroller Layout (the only one that matters)
scroller_structs=20
scroller_default_proportion=0.9
scroller_focus_center=0 # experiment with this one, see how u feel. maybe have a keybind to toggle
scroller_prefer_overspread=1 # disable this one to use scroller_focus_center. this takes higher priority
edge_scroller_pointer_focus=1
edge_scroller_focus_allow_speed=0.0
scroller_proportion_preset=0.5,0.8,1.0
scroller_default_proportion_single=1

# Overview Mode (Alt+Tab)
enable_hotarea=0
ov_tab_mode=1
overviewgappo=30
ov_no_resize=1
