##############
## DA RULES ##
##############
#
# man fuck this
#

##################
## Window Rules ##
##################

# nothing to see here

###############
## Tag Rules ##
###############

# set all of them to scroller. all the other ones suck
# i use mango instead of niri cause i like the logo better
tagrule=id:0,layout_name:scroller
tagrule=id:1,layout_name:scroller
tagrule=id:2,layout_name:scroller
tagrule=id:3,layout_name:scroller
tagrule=id:4,layout_name:scroller
tagrule=id:5,layout_name:scroller
tagrule=id:6,layout_name:scroller
tagrule=id:7,layout_name:scroller
tagrule=id:8,layout_name:scroller
tagrule=id:9,layout_name:scroller

#################
## Layer Rules ##
#################

layerrule=noanim:0,animation_type_open:fade,animation_type_close:fade,layer_name:fuzzel
