######################################################
## my love for quake-style terminals goes unmatched ##
######################################################

scratchpad_cross_monitor=1
windowrule=isnamedscratchpad:1,width:.90,height:.5,offsety:-100,title:alacritty-quake,unfocused_opacity:0.8,focused_opacity:0.8,animation_type_open:none,animation_type_close:none,isglobal:1
bind=NONE,XF86AudioMedia,toggle_named_scratchpad,none,alacritty-quake,alacritty -T alacritty-quake

